language: objective-c
osx_image: beta-xcode6.3
script:
  - xctool -project HTKDynamicResizingCellDemo/HTKDynamicResizingCellDemo.xcodeproj -scheme HTKDynamicResizingCellDemo -sdk iphonesimulator clean build
